simulation:
  domain:
    Nx: 4000
    Ny: 2000
    Nz: 1
physics:
  temperature: 300.0
  GasConstant: 287.058
  pressure: 100000
  density: 1.0
  gamma: 1.0
  viscosity: 0.0005188
  cv: 1.4
domain:
  mx: -1500
  px: 1500
general_boundaries:
  boundary_enable: true
  default_boundary: false
  nozzle_flow: false
wall_boundaries:
  x: 1
  y: 0
boundary_files:
  boundary: /home/dominykas/Desktop/shockFlowProject/FlowPastWedge/sphere.bin
  normals: /home/dominykas/Desktop/shockFlowProject/FlowPastWedge/spheren.bin
v_inf_x: 1.6
T_MAX: 0.698
riemann: false
shock:
  P_ratio: 1
  T_ratio: 1
  location: 20000
  trigger: 1e-3
  trigger2: 2
  trigger3: 10.001
render_window:
  x: 2000
  y: 1000
events:
  EXT:
    time: 200
capture_events:
  EXT:
    time: 200
output:
  path: ../Results/Videos/nieuw/
runtime:
  solver:
    alphaMode: false
    kernel_debug: false
    Dynamic_weights: false
wedge:
  width: 800
  height: 200
  char_height: 20
  noseX: 0.1
  noseY: 0.5
bc_scale: 1
fields_to_rasterize:
  field1:
    id: 0
    min: 0.4
    max: 0.0
    autoset: false
    output: M15.mp4
